- name: インストール
  url: ./install.md
- name: 基本操作
  content:
    - name: 概要
      url: ./overview.md
    - name: ファイル操作
      url: ./file-operations.md
    - name: ディレクトリ操作
      url: ./directory-operations.md
    - name: ディレクトリマウント
      url: ./directory-mounting.md
    - name: ファイルの移動とコピー
      url: ./move-and-copy.md
    - name: ファイルハンドル比較
      url: ./handle-comparison.md
    - name: ファイル変更監視
      url: ./file-observation.md
    - name: sw.js設定のヒント
      url: ./sw-advanced.md